//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanoramaJXNU.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.Comment1 = new HashSet<Comment>();
            this.ReplyPraiseRecord = new HashSet<ReplyPraiseRecord>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Content { get; set; }
        public System.DateTime CreatTime { get; set; }
        public Nullable<int> CommentId { get; set; }
        public int TopicId { get; set; }
        public int Status { get; set; }
        public int TopicUserId { get; set; }
        public Nullable<int> Praise { get; set; }
        public string UserImg { get; set; }
        public string TopicTitle { get; set; }
    
        public virtual ICollection<Comment> Comment1 { get; set; }
        public virtual Comment Comment2 { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
        public virtual ICollection<ReplyPraiseRecord> ReplyPraiseRecord { get; set; }
    }
}
