//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanoramaJXNU.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Panorama_JXNUEntities : DbContext
    {
        public Panorama_JXNUEntities()
            : base("name=Panorama_JXNUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Collect> Collect { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Focus> Focus { get; set; }
        public virtual DbSet<LeaveMsg> LeaveMsg { get; set; }
        public virtual DbSet<ReplyPraiseRecord> ReplyPraiseRecord { get; set; }
        public virtual DbSet<Topic> Topic { get; set; }
        public virtual DbSet<TopicPraiseRecord> TopicPraiseRecord { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<PanoCollect> PanoCollect { get; set; }
        public virtual DbSet<PanoPraiseRecord> PanoPraiseRecord { get; set; }
    }
}
