//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanoramaJXNU.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.Collect = new HashSet<Collect>();
            this.TopicPraiseRecord = new HashSet<TopicPraiseRecord>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int ReplyCount { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int PraiseCount { get; set; }
        public int BroseCount { get; set; }
        public byte Status { get; set; }
    
        public virtual ICollection<Collect> Collect { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<TopicPraiseRecord> TopicPraiseRecord { get; set; }
    }
}
